// Build i18n.ts from the english base + the 13-language translation set.
const fs = require('fs')
const en = JSON.parse(fs.readFileSync('D:/aetherai/app/src/utils/i18n-en-base.json', 'utf-8'))
const data = JSON.parse(fs.readFileSync('D:/aetherai/app/src/utils/i18n-translations.json', 'utf-8'))

// Upside-down English: reverse the string and swap a few letters so it reads
// upside-down. Cosmetic joke locale, not a real translation.
const F = { a: 'ɐ', b: 'q', c: 'ɔ', d: 'p', e: 'ǝ', f: 'ɟ', g: 'ƃ', h: 'ɥ', i: 'ᴉ', j: 'ɾ', k: 'ʞ', l: 'l', m: 'ɯ', n: 'u', o: 'o', p: 'd', q: 'b', r: 'ɹ', s: 's', t: 'ʇ', u: 'n', v: 'ʌ', w: 'ʍ', x: 'x', y: 'ʎ', z: 'z' }
function flip(s) {
  return s.split('').map(c => F[c.toLowerCase()] || c).reverse().join('')
}
const enUpside = {}
for (const k in en) enUpside[k] = flip(en[k])

const translations = { en, 'en-upside': enUpside }
for (const r of data) translations[r.lang] = r.strings

const langs = [
  { code: 'en', label: 'English', native: 'English', dir: 'ltr' },
  { code: 'en-upside', label: 'English (uʍoᗁ ǝpᴉsd∩)', native: 'English', dir: 'ltr' },
  { code: 'zh-CN', label: 'Chinese (Simplified)', native: '简体中文', dir: 'ltr' },
  { code: 'zh-TW', label: 'Chinese (Traditional)', native: '繁體中文', dir: 'ltr' },
  { code: 'zh-WEN', label: 'Chinese (Classical)', native: '文言文', dir: 'ltr' },
  { code: 'ja', label: 'Japanese', native: '日本語', dir: 'ltr' },
  { code: 'es', label: 'Spanish', native: 'español', dir: 'ltr' },
  { code: 'fr', label: 'French', native: 'français', dir: 'ltr' },
  { code: 'de', label: 'German', native: 'Deutsch', dir: 'ltr' },
  { code: 'pt', label: 'Portuguese', native: 'português', dir: 'ltr' },
  { code: 'ru', label: 'Russian', native: 'русский', dir: 'ltr' },
  { code: 'uk', label: 'Ukrainian', native: 'українська', dir: 'ltr' },
  { code: 'ar', label: 'Arabic', native: 'العربية', dir: 'rtl' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', dir: 'ltr' },
  { code: 'ko', label: 'Korean', native: '한국어', dir: 'ltr' },
]

const code = `// AUTO-GENERATED by gen-i18n.js. Do not edit by hand — regenerate from
// i18n-en-base.json + i18n-translations.json.

export type LangCode = ${langs.map(l => "'" + l.code + "'").join(' | ')}

export const LANGS = ${JSON.stringify(langs, null, 2)} as const

const translations: Record<string, Record<string, string>> = ${JSON.stringify(translations, null, 2)}

// Current active language. Held as a module-level variable so \`t()\` can read it
// without importing the store (avoids a circular dep: store imports \`t\`).
let currentLang: LangCode = 'en'
export function setLang(code: LangCode) { currentLang = code }
export function getLang(): LangCode { return currentLang }

// Detect the user's system language and map to a supported code. Falls back to en.
export function detectLang(): LangCode {
  const n = (navigator.language || "en").toLowerCase()
  if (n.startsWith("zh")) {
    if (n.includes("tw") || n.includes("hant") || n.includes("hk")) return "zh-TW"
    return "zh-CN"
  }
  for (const l of LANGS) {
    if (n.startsWith(l.code.toLowerCase())) return l.code as LangCode
  }
  return "en"
}

export function t(key: string, ...args: (string | number)[]): string {
  const table = translations[currentLang] || translations["en"] || {}
  let s = table[key] ?? translations["en"]?.[key] ?? key
  if (args.length) {
    s = s.replace(/\\{(\\d+)\\}/g, (_, i) => String(args[Number(i)] ?? ""))
  }
  return s
}

export function getLangDir(code: string): "ltr" | "rtl" {
  return (LANGS.find((l) => l.code === code)?.dir as "ltr" | "rtl") || "ltr"
}
`
fs.writeFileSync('D:/aetherai/app/src/utils/i18n.ts', code)
console.log('i18n.ts generated:', langs.length, 'locales,', Object.keys(en).length, 'keys each')
